spring:
  application:
    name: service-word
  profiles:
    active: dev

server:
  servlet:
    context-path: /api

---
server:
  port: 20002

eureka:
  client:
    enabled: false

spring:
  profiles: dev
  datasource:
    url: ${HELO_DB_URL}
    username: ${HELO_DB_USERNAME}
    password: ${HELO_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL55Dialect
      ddl-auto: none

logging:
  level:
    org.springframework: debug

---
server:
  port: 80

spring:
  profiles: prod

  cloud:
    service-registry:
      auto-registration:
        enabled: true

  datasource:
    url: ${HELO_DB_URL}
    username: ${HELO_DB_USERNAME}
    password: ${HELO_DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.MySQL55Dialect
      ddl-auto: none
logging:
  level:
    org.springframework: error

